In [1]:
#Exp no.:

In [ ]:
#Aim: Basic of data frame

In [ ]:
# Name: Prerna C Dhanorkar
# Roll no: 47
# Sec: 3yr c 
# Subject:
# Date:

# Creating Series

In [26]:
# Program for creating Series using series() method of Pandas Library

In [27]:
#Import Pandas library
import pandas as pd

In [28]:
#Creating Student Name List
Name=["Ashish","Sagar","Shrikant","Lovly","Saurabh"]
Name

['Ashish', 'Sagar', 'Shrikant', 'Lovly', 'Saurabh']

In [29]:
#Creating a Series 
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1      Ashish
2       Sagar
3    Shrikant
4       Lovly
5     Saurabh
dtype: object

# Creating Data Frame

In [30]:
#Import Pandas library
import pandas as pd

In [31]:
#Creating Data Frame
df=pd.DataFrame([[10,12,14,16],[11,18,15,21],[12,13,14,15]],
columns= ["BIA","DBMS","DSS","CAO"])

In [32]:
df

   BIA  DBMS  DSS  CAO
0   10    12   14   16
1   11    18   15   21
2   12    13   14   15

In [33]:
df.shape

(3, 4)

In [34]:
df.size

12

In [35]:
df.ndim

2

# Adding Record (Row) to the data frame

In [36]:
df2=pd.DataFrame([[5,6,7,8]],
columns= ["BIA","DBMS","DSS","CAO"])

In [37]:
import pandas as pd
df3 = pd.concat([df, df2], ignore_index=True)

In [38]:
df3

   BIA  DBMS  DSS  CAO
0   10    12   14   16
1   11    18   15   21
2   12    13   14   15
3    5     6    7    8

# Adding Attribute (Columns) name DM

In [39]:
df3["DM"]=[12,15,16,14]

In [40]:
df3

   BIA  DBMS  DSS  CAO  DM
0   10    12   14   16  12
1   11    18   15   21  15
2   12    13   14   15  16
3    5     6    7    8  14

# Deleting Record from  df3 dataframe

In [41]:
df4=df3.drop(index=[1])

In [42]:
df4

   BIA  DBMS  DSS  CAO  DM
0   10    12   14   16  12
2   12    13   14   15  16
3    5     6    7    8  14

# Deleting Attribute (Columns) from df3 dataframe

In [43]:
df5=df3.drop(columns=["DM"])

In [44]:
df5

   BIA  DBMS  DSS  CAO
0   10    12   14   16
1   11    18   15   21
2   12    13   14   15
3    5     6    7    8

In [45]:
#Finding mean of DSS 

print("Mean of DSS:", df5["DSS"].mean())

Mean of DSS: 12.5

In [46]:
#Finding median of DSS

print("Median of DSS:", df5["DSS"].median())

Median of DSS: 14.0

In [47]:
#Finding mode of DSS

print("Mode of DSS:", df5["DSS"].mode())

Mode of DSS: 0    14
Name: DSS, dtype: int64

In [48]:
#Finding max number of DSS

print("Max of DSS:", df5["DSS"].max())

Max of DSS: 15

In [49]:
#Finding Min number of DSS

print("Max of DSS:", df5["DSS"].min())

Max of DSS: 7